version: '2'

services:
  bikesharing-marketing:
    image: user/bikesharing-marketing
    build:
      context: ./src/BikeSharing-Marketing
      dockerfile: Dockerfile
      args:
        source: ${DOCKER_BUILD_SOURCE}
    expose:
      - "80"
