version: '2'

services:
  marketing:
    image: bikesharing/marketing
    build:
      context: ./src/Marketing
      dockerfile: Dockerfile
      args:
        source: ${DOCKER_BUILD_SOURCE}
