version: '2'

services:
  marketing:
    build:
      context: ./src/Marketing
      dockerfile: Dockerfile
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
