version: '2'
services:
  build:
    build:
        context: ./build
        dockerfile: Dockerfile
    image: microsoft/aspnetcore:1.0.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore3 && dotnet publish3 -c Release -o ./bin/Release/PublishOutput"
